Update dart.yml

diff --git a/.github/workflows/dart.yml b/.github/workflows/dart.yml
--- a/.github/workflows/dart.yml
+++ b/.github/workflows/dart.yml
@@ -32,29 +32,32 @@ jobs:
       # Añadir los assets al pubspec.yaml sin duplicar la clave flutter:
       - name: Ensure assets configuration in pubspec.yaml
         run: |
-          if ! grep -q "assets/html/mi_carnet_vip_canjear.html" pubspec.yaml; then
+          if ! grep -q "assets/mi_carnet_vip_canjear.html" pubspec.yaml; then
             echo "Añadiendo assets al pubspec.yaml"
             if ! grep -q "^flutter:" pubspec.yaml; then
               echo "flutter:" >> pubspec.yaml
               echo "  assets:" >> pubspec.yaml
-              echo "    - assets/html/mi_carnet_vip_canjear.html" >> pubspec.yaml
+              echo "    - assets/mi_carnet_vip_canjear.html" >> pubspec.yaml
             else
               if ! grep -q "assets:" pubspec.yaml; then
                 sed -i '' '/flutter:/a\
           assets:
                 ' pubspec.yaml
               fi
-              echo "    - assets/html/mi_carnet_vip_canjear.html" >> pubspec.yaml
+              echo "    - assets/mi_carnet_vip_canjear.html" >> pubspec.yaml
             fi
           fi
 
-      # Verifica si el archivo HTML está en el lugar correcto
+      # Verifica si el archivo HTML está en el lugar correcto (en la raíz)
       - name: Ensure HTML file exists
         run: |
-          mkdir -p assets/html
-          if [ ! -f assets/html/mi_carnet_vip_canjear.html ]; then
-            echo "Error: El archivo assets/html/mi_carnet_vip_canjear.html no existe."
+          if [ ! -f mi_carnet_vip_canjear.html ]; then
+            echo "Error: El archivo mi_carnet_vip_canjear.html no existe en la raíz."
             exit 1
+          else
+            echo "El archivo mi_carnet_vip_canjear.html existe en la raíz, moviéndolo a assets/html..."
+            mkdir -p assets
+            mv mi_carnet_vip_canjear.html assets/
           fi
 
       # Instala las dependencias del proyecto Flutter
