Update dart.yml

diff --git a/.github/workflows/dart.yml b/.github/workflows/dart.yml
--- a/.github/workflows/dart.yml
+++ b/.github/workflows/dart.yml
@@ -27,22 +27,26 @@ jobs:
         run: npm install
         working-directory: ./  # Asegúrate de estar en la raíz del proyecto
 
-      # Add iOS platform (if not already added)
-      - name: Add iOS platform
-        run: cordova platform add ios
-        working-directory: ./  # Asegúrate de estar en la raíz del proyecto
-
-      # Verify if Podfile exists
-      - name: Verify Podfile exists
+      # Check if iOS platform is already added
+      - name: Check for iOS platform
+        id: check_ios
         run: |
-          if [ ! -f platforms/ios/Podfile ]; then
-            echo "Podfile not found. Something went wrong when adding the iOS platform."
-            exit 1
+          if ! cordova platform ls | grep -q ios; then
+            echo "iOS platform not found, adding..."
+            cordova platform add ios
+          else
+            echo "iOS platform already added."
           fi
 
       # Install CocoaPods dependencies for iOS
       - name: Install CocoaPods
-        run: pod install --project-directory=platforms/ios
+        run: |
+          if [ -f platforms/ios/Podfile ]; then
+            pod install --project-directory=platforms/ios
+          else
+            echo "Podfile not found. Something went wrong when adding the iOS platform."
+            exit 1
+          fi
 
       # Build the Cordova iOS app
       - name: Build iOS app
