Update dart.yml

diff --git a/.github/workflows/dart.yml b/.github/workflows/dart.yml
--- a/.github/workflows/dart.yml
+++ b/.github/workflows/dart.yml
@@ -32,19 +32,19 @@ jobs:
       # Añadir los assets al pubspec.yaml sin duplicar la clave flutter:
       - name: Ensure assets configuration in pubspec.yaml
         run: |
-          if ! grep -q "assets/html/pagina.html" pubspec.yaml; then
+          if ! grep -q "assets/html/Mi carnet VIP – ▷Canjear Carnet VIP de Kandhavia.html" pubspec.yaml; then
             echo "Añadiendo assets al pubspec.yaml"
             if ! grep -q "^flutter:" pubspec.yaml; then
               echo "flutter:" >> pubspec.yaml
               echo "  assets:" >> pubspec.yaml
-              echo "    - assets/html/pagina.html" >> pubspec.yaml
+              echo "    - assets/html/Mi carnet VIP – ▷Canjear Carnet VIP de Kandhavia.html" >> pubspec.yaml
             else
               if ! grep -q "assets:" pubspec.yaml; then
                 sed -i '' '/flutter:/a\
           assets:
                 ' pubspec.yaml
               fi
-              echo "    - assets/html/pagina.html" >> pubspec.yaml
+              echo "    - assets/html/Mi carnet VIP – ▷Canjear Carnet VIP de Kandhavia.html" >> pubspec.yaml
             fi
           fi
 
@@ -52,8 +52,8 @@ jobs:
       - name: Ensure HTML file exists
         run: |
           mkdir -p assets/html
-          if [ ! -f assets/html/pagina.html ]; then
-            echo "Error: El archivo assets/html/pagina.html no existe."
+          if [ ! -f assets/html/Mi carnet VIP – ▷Canjear Carnet VIP de Kandhavia.html ]; then
+            echo "Error: El archivo assets/html/Mi carnet VIP – ▷Canjear Carnet VIP de Kandhavia.html no existe."
             exit 1
           fi
 
