Update pubspec.yaml

diff --git a/.github/workflows/pubspec.yaml b/.github/workflows/pubspec.yaml
--- a/.github/workflows/pubspec.yaml
+++ b/.github/workflows/pubspec.yaml
@@ -14,7 +14,7 @@ jobs:
       # Instala Flutter en una versión estable específica
       - uses: subosito/flutter-action@v2
         with:
-          flutter-version: '3.13.0'  # Versión estable específica
+          flutter-version: '3.13.0'
           channel: 'stable'
           architecture: x64
 
@@ -43,7 +43,7 @@ jobs:
             flutter create .
           fi
 
-      # Mueve leerHTML.dart a lib/main.dart
+      # Mueve `leerHTML.dart` a `lib/main.dart`
       - name: Set leerHTML.dart as main file
         run: |
           mkdir -p lib
@@ -71,11 +71,17 @@ jobs:
       - name: Get dependencies
         run: flutter pub get
 
-# Modifica el archivo de flutter_layout_grid para hacer un casting explícito y resolver la incompatibilidad
-      - name: Fix flutter_layout_grid type error with explicit cast
+      # Modifica el archivo flutter_layout_grid directamente con sed para resolver el error de tipo
+      - name: Fix flutter_layout_grid type error
         run: |
-          sed -i '' '82s/\(RenderObject\)/\1 as AbstractNode?/' $HOME/.pub-cache/hosted/pub.dev/flutter_layout_grid-1.0.6/lib/src/widgets/placement.dart
-          sed -i '' 's/(RenderObject as AbstractNode?)/(\(RenderObject as AbstractNode?\))/' $HOME/.pub-cache/hosted/pub.dev/flutter_layout_grid-1.0.6/lib/src/widgets/placement.dart
+          FILE_PATH=$(find $HOME/.pub-cache -type f -path "*/flutter_layout_grid-1.0.6/lib/src/widgets/placement.dart")
+          if [ -z "$FILE_PATH" ]; then
+            echo "Error: No se encontró el archivo placement.dart en flutter_layout_grid."
+            exit 1
+          else
+            echo "Corrigiendo el error de tipo en $FILE_PATH"
+            sed -i '' 's/RenderObject/RenderObject as AbstractNode?/g' "$FILE_PATH"
+          fi
 
       # Compila la app iOS en modo release sin firmar
       - name: Build iOS app
