Update pubspec.yaml

diff --git a/.github/workflows/pubspec.yaml b/.github/workflows/pubspec.yaml
--- a/.github/workflows/pubspec.yaml
+++ b/.github/workflows/pubspec.yaml
@@ -11,6 +11,12 @@ jobs:
       # Clona el repositorio
       - uses: actions/checkout@v3
 
+      # Paso de depuración: listar el contenido del directorio para verificar la estructura inicial
+      - name: List directory content after checkout
+        run: |
+          echo "Contenido del directorio después del checkout:"
+          ls -la
+
       # Instala Flutter usando el canal estable y la arquitectura x64
       - uses: subosito/flutter-action@v2
         with:
@@ -24,29 +30,40 @@ jobs:
             flutter create .
           fi
 
-      # Paso de depuración: listar el contenido del directorio
-      - name: List directory content
+      # Listar contenido del directorio después de crear el proyecto
+      - name: List directory content after project creation
         run: |
-          echo "Contenido del directorio actual:"
+          echo "Contenido del directorio después de la creación del proyecto:"
           ls -la
 
-      # Reemplaza el archivo main.dart generado por el archivo Dart personalizado
-      - name: Replace main.dart with custom Dart file
+      # Asegúrate de que el archivo leerHTML.dart exista en la ruta correcta (directamente en la raíz o en lib/)
+      - name: Ensure leerHTML.dart exists and move to lib/
         run: |
-          echo "Reemplazando main.dart con el archivo personalizado..."
-          mv lib/leerHTML.dart lib/main.dart
+          if [ -f leerHTML.dart ]; then
+            echo "Mover leerHTML.dart a lib/"
+            mv leerHTML.dart lib/
+          elif [ ! -f lib/leerHTML.dart ]; then
+            echo "Error: leerHTML.dart no existe en la raíz ni en lib/."
+            exit 1
+          fi
 
-      # Verifica si el archivo HTML está en el lugar correcto (en la raíz)
+      # Asegúrate de que el archivo HTML esté en la raíz y muévelo a la carpeta de assets
       - name: Ensure HTML file exists
         run: |
           if [ ! -f mi_carnet_vip_canjear.html ]; then
             echo "Error: El archivo mi_carnet_vip_canjear.html no existe en la raíz."
             exit 1
           else
-            echo "El archivo mi_carnet_vip_canjear.html existe en la raíz, moviéndolo a assets/html..."
+            echo "Moviendo el archivo mi_carnet_vip_canjear.html a assets/html..."
             mkdir -p assets/html
             mv mi_carnet_vip_canjear.html assets/html/
           fi
+
+      # Listar el contenido del directorio para asegurarnos de que los archivos están en su lugar
+      - name: List directory content before build
+        run: |
+          echo "Contenido del directorio antes de la compilación:"
+          ls -la
 
       # Limpia y reinstala las dependencias del proyecto Flutter
       - name: Clean and get dependencies
